### ISSUE TITLE
Position on Field (POF)

### ISSUE THREAD

**Issue by WesleyMcGinn** [Bionic-Bison-5535/FORTE#10]
The Limelight and NavX should be used to constantly find the position of the robot.  Whenever an AprilTag is in view while the robot is driving, the robot should recalculate its position.  Otherwise, it should calculate the change its known position based on its current vector of motion.

This will allow us to:
 - Have excellent autonomous `goToPos([x,y])` functionality for picking up notes at set positions
 - Stay in the alliance zone during autonomous
 - Have easy ability to quickly go to specific position on field, such as the amp, with one press of a button
 - Record robot position during matches to watch back later in the SmartDashboard

The position-finding system should have its own file and its own class, with functions for setting and retrieving the robot's position.

This will give us a major software advantage over other teams.

**Comment by WesleyMcGinn** [comment]
## Possibly helpful information on Limelight's Online Documentation:
[Robot Localisation with MegaTag](https://docs.limelightvision.io/docs/docs-limelight/pipeline-apriltag/apriltag-robot-localization) - How to easily find robot's position on the field
[Complete NetworkTables API](https://docs.limelightvision.io/docs/docs-limelight/apis/complete-networktables-api) - All NT Variable Names and How to Access in Java

**Comment by Ethanmejia** [comment]
We have a better system right now; POF would not make us much better.
