### ISSUE TITLE
Note Defence Comeback Operation (NDCO)

### ISSUE THREAD

**Issue by WesleyMcGinn** [Bionic-Bison-5535/FORTE#11]
The robot is only allowed to hold one note at a time.  If a note gets stuck on the robot, it's over for us for the rest of the match.  This being so, we must have a defence mechanism to run in case a note somehow ends up on top of the robot.

If a note does get stock on the top of the robot, we could collect it by doing the following:
 - Move launcher slightly up (angled to launch a little lower), so that the bottom of the launcher is aligned with the top of the upper intake belt.
 - Run the launcher's intake without running the intake belts
 - Run intake belts backwards, conveying the note upwards and into the launcher
 - When launcher detects captured note, robot is ready to launch it

This would make an epic comeback from what looks like the end of the game for us:
**Game Narrator:** "Oh!  And it looks like team 5535 has a note stuck on top of their robot!  Guess it's the end of the game for the blue alliance."
**A few seconds later:** "HOW ABOUT THAT! (crowd cheers)  Looks like team 5535 has made an epic comeback, capturing the note that was set on their robot and now launching that note into the amplified speaker!  Way to go team 5535!  That was awesome!"

Thus, the NDCO (Note Defence Comeback Operation).

We have to program this.

**Comment by Ethanmejia** [comment]
We will be covering the intake with plexiglass. The note can't pull up from the intake. We will not be fixing this. :(
